spring:
  application:
    name: notification-service
  thymeleaf:
    cache: false
    prefix: classpath://templates/
    suffix: .html
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:achrafabdelfadel416@gmail.com}
    password: ${MAIL_PASSWORD:bnvg wyhr 34343 3232 avte}
    properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000
    test-connection: false

server:
  port: 8087

logging:
  level:
    com.logistics.notification: DEBUG
    org.springframework.web: INFO
    org.springframework.mail: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
