spring.application.name=route-service
server.port=8089

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.datasource.url=jdbc:postgresql://ep-purple-la43ke-a4kfv14p-pooler.us-east-1.aws.neon.tech:5432/routes_db?sslmode=require&channel_binding=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_8mu434WSj5hzkCV
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update